spring.application.name=LiveScoreApp
spring.datasource.url=jdbc:mysql://localhost:3306/livescore
spring.datasource.username=root

spring.datasource.password=Tharun$23




spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=TXlTdXBlclNlY3JldEtleUZvclNwb3J0c0Zlc3RQcm9qZWN0MTIzNDU2Nzg5
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG